@extends('layouts.default')

@section('title', 'Obtain Rolex Year by Serial Numbers')

@section ('header')
<link href="fancybox/jquery.fancybox.min.css" rel="stylesheet">
@endsection

@section ('content')
<h2>Serial Number lookup.</h2>
<hr>
<div class="content">
    <div style="background: #fff; padding: 30px 25px;border-radius: 4px;">
        <div class="container">
            <h3>Find Your Rolex Production Year by Serial Number</h3>

            <table class="table table-striped">
                <tbody>
                    <tr>
                        <th>Year</th>
                        <th>Serial</th>
                    </tr>
                    <tr>
                        <td>2011 – Present</td>
                        <td>Random/Mixed</td>
                    </tr>
                    <tr>
                        <td>2010</td>
                        <td>G</td>
                    </tr>
                    <tr>
                        <td>2009</td>
                        <td>V</td>
                    </tr>
                    <tr>
                        <td>2008</td>
                        <td>M or V</td>
                    </tr>
                    <tr>
                        <td>2007</td>
                        <td>M or Z</td>
                    </tr>
                    <tr>
                        <td>2006</td>
                        <td>Z</td>
                    </tr>
                    <tr>
                        <td>2005</td>
                        <td>D</td>
                    </tr>
                    <tr>
                        <td>2004</td>
                        <td>F</td>
                    </tr>
                    <tr>
                        <td>2003</td>
                        <td>F</td>
                    </tr>
                    <tr>
                        <td>2002</td>
                        <td>Y</td>
                    </tr>
                    <tr>
                        <td>2000</td>
                        <td>P</td>
                    </tr>
                    <tr>
                        <td>1999</td>
                        <td>A</td>
                    </tr>
                    <tr>
                        <td>1998</td>
                        <td>U</td>
                    </tr>
                    <tr>
                        <td>1997</td>
                        <td>U</td>
                    </tr>
                    <tr>
                        <td>1996</td>
                        <td>T</td>
                    </tr>
                    <tr>
                        <td>1995</td>
                        <td>W</td>
                    </tr>
                    <tr>
                        <td>1994</td>
                        <td>S</td>
                    </tr>
                    <tr>
                        <td>1993</td>
                        <td>S</td>
                    </tr>
                    <tr>
                        <td>1992</td>
                        <td>C</td>
                    </tr>
                    <tr>
                        <td>1991</td>
                        <td>X or N</td>
                    </tr>
                    <tr>
                        <td>1990</td>
                        <td>E</td>
                    </tr>
                    <tr>
                        <td>1989</td>
                        <td>L</td>
                    </tr>
                    <tr>
                        <td>1988</td>
                        <td>R</td>
                    </tr>
                    <tr>
                        <td>1987</td>
                        <td>9,760,000</td>
                    </tr>
                    <tr>
                        <td>1986</td>
                        <td>9,300,000</td>
                    </tr>
                    <tr>
                        <td>1985</td>
                        <td>8,814,000</td>
                    </tr>
                    <tr>
                        <td>1984</td>
                        <td>8,388,000</td>
                    </tr>
                    <tr>
                        <td>1983</td>
                        <td>7,860,000</td>
                    </tr>
                    <tr>
                        <td>1982</td>
                        <td>7,366,000</td>
                    </tr>
                    <tr>
                        <td>1981</td>
                        <td>6,910,000</td>
                    </tr>
                    <tr>
                        <td>1980</td>
                        <td>6,430,000</td>
                    </tr>
                    <tr>
                        <td>1979</td>
                        <td>5,959,000</td>
                    </tr>
                    <tr>
                        <td>1978</td>
                        <td>5,481,000</td>
                    </tr>
                    <tr>
                        <td>1977</td>
                        <td>5,005,000</td>
                    </tr>
                    <tr>
                        <td>1976</td>
                        <td>4,535,000</td>
                    </tr>
                    <tr>
                        <td>1975</td>
                        <td>4,265,000</td>
                    </tr>
                    <tr>
                        <td>1974</td>
                        <td>4,000,000</td>
                    </tr>
                    <tr>
                        <td>1973</td>
                        <td>3,741,000</td>
                    </tr>
                    <tr>
                        <td>1972</td>
                        <td>3,478,000</td>
                    </tr>
                    <tr>
                        <td>1971</td>
                        <td>3,215,000</td>
                    </tr>
                    <tr>
                        <td>1970</td>
                        <td>2,952,000</td>
                    </tr>
                    <tr>
                        <td>1969</td>
                        <td>2,689,000</td>
                    </tr>
                    <tr>
                        <td>1968</td>
                        <td>2,426,000</td>
                    </tr>
                    <tr>
                        <td>1967</td>
                        <td>2,164,000</td>
                    </tr>
                    <tr>
                        <td>1966</td>
                        <td>1,870,000</td>
                    </tr>
                    <tr>
                        <td>1965</td>
                        <td>1,791,000</td>
                    </tr>
                    <tr>
                        <td>1964</td>
                        <td>1,713,000</td>
                    </tr>
                    <tr>
                        <td>1963</td>
                        <td>1,635,000</td>
                    </tr>
                    <tr>
                        <td>1962</td>
                        <td>1,557,000</td>
                    </tr>
                    <tr>
                        <td>1961</td>
                        <td>1,485,000</td>
                    </tr>
                    <tr>
                        <td>1960</td>
                        <td>1,401,000</td>
                    </tr>
                    <tr>
                        <td>1959</td>
                        <td>1,323,000</td>
                    </tr>
                    <tr>
                        <td>1958</td>
                        <td>1,245,000</td>
                    </tr>
                    <tr>
                        <td>1957</td>
                        <td>1,167,000</td>
                    </tr>
                    <tr>
                        <td>1956</td>
                        <td>1,095,000</td>
                    </tr>
                    <tr>
                        <td>1955</td>
                        <td>1,010,000</td>
                    </tr>
                    <tr>
                        <td>1954</td>
                        <td>935,000</td>
                    </tr>
                    <tr>
                        <td>1953</td>
                        <td>869,000</td>
                    </tr>
                    <tr>
                        <td>1952</td>
                        <td>804,000</td>
                    </tr>
                    <tr>
                        <td>1951</td>
                        <td>735,000</td>
                    </tr>
                    <tr>
                        <td>1950</td>
                        <td>372,000</td>
                    </tr>
                    <tr>
                        <td>1949</td>
                        <td>608,000</td>
                    </tr>
                    <tr>
                        <td>1948</td>
                        <td>543,000</td>
                    </tr>
                    <tr>
                        <td>1947</td>
                        <td>478,000</td>
                    </tr>
                    <tr>
                        <td>1946</td>
                        <td>413,000</td>
                    </tr>
                    <tr>
                        <td>1945</td>
                        <td>348,000</td>
                    </tr>
                    <tr>
                        <td>1944</td>
                        <td>284,000</td>
                    </tr>
                    <tr>
                        <td>1943</td>
                        <td>253,000</td>
                    </tr>
                    <tr>
                        <td>1942</td>
                        <td>224,000</td>
                    </tr>
                    <tr>
                        <td>1941</td>
                        <td>194,000</td>
                    </tr>
                    <tr>
                        <td>1940</td>
                        <td>165,000</td>
                    </tr>
                    <tr>
                        <td>1939</td>
                        <td>136,000</td>
                    </tr>
                    <tr>
                        <td>1938</td>
                        <td>118,000</td>
                    </tr>
                    <tr>
                        <td>1937</td>
                        <td>98,000</td>
                    </tr>
                    <tr>
                        <td>1936</td>
                        <td>82,000</td>
                    </tr>
                    <tr>
                        <td>1935</td>
                        <td>62,000</td>
                    </tr>
                    <tr>
                        <td>1934</td>
                        <td>55,000</td>
                    </tr>
                    <tr>
                        <td>1933</td>
                        <td>49,000</td>
                    </tr>
                    <tr>
                        <td>1932</td>
                        <td>43,000</td>
                    </tr>
                    <tr>
                        <td>1931</td>
                        <td>40,000</td>
                    </tr>
                    <tr>
                        <td>1930</td>
                        <td>38,000</td>
                    </tr>
                    <tr>
                        <td>1929</td>
                        <td>35,000</td>
                    </tr>
                    <tr>
                        <td>1928</td>
                        <td>33,000</td>
                    </tr>
                    <tr>
                        <td>1927</td>
                        <td>3,000</td>
                    </tr>
                    <tr>
                        <td>1926</td>
                        <td>28,000</td>
                    </tr>
                    <tr>
                        <td>1925</td>
                        <td>25,000</td>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>
</div>
@endsection

@section ('footer')
    <script>
        window.ParsleyConfig = {
            errorsWrapper: '<div></div>',
            errorTemplate: '<div class="alert alert-danger parsley" role="alert"></div>',
            errorClass: 'has-error',
            successClass: 'has-success'
        };
    </script>
    <script src="{{ asset('/public/fancybox/jquery.fancybox.min.js') }}"></script>
    <script src="{{ asset('/public/js/parsley.js') }}"></script>
@endsection
