<?php

namespace App\Services;

use App\Models\ChatMessage;
use App\Models\User;
use App\Events\MessagesEvent;
use App\Notifications\NewMessage;
use Illuminate\Support\Facades\Notification;
use Illuminate\Support\Facades\Log;
use Illuminate\Support\Facades\Storage; // *** NEW: Import Storage facade ***
use Illuminate\Support\Facades\File;     // *** NEW: Import File facade ***
use Illuminate\Support\Str;              // *** NEW: Import Str facade for UUID ***

class ChatService
{
    /**
     * Store a new chat message and dispatch related events/notifications.
     *
     * @param int $senderId The ID of the message sender.
     * @param int $receiverId The ID of the message receiver.
     * @param string $messageContent The content of the message.
     * @param string|null $uploadedTempImagePath Optional path to a temporary uploaded image (e.g., from Livewire or iOS).
     * This should be a path relative to storage/app/public/images/
     * @param \Illuminate\Http\UploadedFile|null $imageFile Livewire UploadedFile instance
     * (if Livewire handles upload directly and you want ChatService to store it)
     * @return \App\Models\ChatMessage The created message.
     */
    public function sendMessage(
        int $senderId,
        int $receiverId,
        string $messageContent,
        // Removed $uploadedTempImagePath for clarity, will use $imageFile if Livewire passes it
        // Or you might design it to accept a public URL if the file is already moved/processed.
        // Let's adapt it for Livewire's direct file handling.
        ?\Illuminate\Http\UploadedFile $imageFile = null // This is the Livewire file object
    ): ChatMessage {
        $imagePathForDb = null;

        // Handle image file if provided (typically from Livewire component)
        if ($imageFile) {
            $ext = $imageFile->getClientOriginalExtension();
            $filename = Str::uuid() . '.' . $ext;

            // Store directly to the desired final public location if possible
            // Or if Livewire already stored it temporarily to 'images', then move it.
            // Let's assume you store to 'public/images/chat' directly via Storage facade
            // This simplifies the manual File::move part from your Livewire component.
            $storedPath = $imageFile->storeAs('images', $filename, 'public');

            // Storage::url() gives the public URL. Remove '/storage' prefix if needed for image_path DB column
            // For example, if your DB column 'image_path' expects '/images/chat/...'
            $imagePathForDb = str_replace('public/', '/', $storedPath); // Assuming public disk stores to storage/app/public
            $imagePathForDb = str_replace('images', '/images/chat', $imagePathForDb); // Adjust based on your Storage::disk('public') root

            $imageLocation = base_path()."/storage/app/public/images/";
            File::move($imageLocation.$filename, public_path("/images/chat/$filename"));
        }

        $message = ChatMessage::create([
            'sender_id' => $senderId,
            'receiver_id' => $receiverId,
            'message' => $messageContent,
            'image_path' => $imagePathForDb, // Use the path generated by Storage::url()
        ]);

        // 2. Broadcast the message event (for Livewire/web clients)
        $sender = User::find($senderId);
        if ($sender) {

            broadcast(new MessagesEvent(
                recipientId: $receiverId,
                senderId: $senderId,
                message: $messageContent,
                createdAt: $message->created_at,
            ))->toOthers();

        } else {
            Log::warning("ChatService: Sender user {$senderId} not found for broadcasting.");
        }

        // 3. Dispatch Push Notification (for iOS mobile clients)
        $recipient = User::find($receiverId);

        if ($recipient && ($recipient->device_token || $recipient->fcm_device_token)) {
            // NewChatMessage expects full public URL for imagePath
            Notification::send(
                $recipient,
                new NewMessage(
                    $messageContent,
                    $sender->name ?? 'Someone',
                    $senderId,
                    $imagePathForDb // Pass image path to notification if it has one
                )
            );
            // Log::info("ChatService: Push Notification dispatched for user {$recipient->id}.");
        } else {
            Log::warning("ChatService: Recipient user {$receiverId} not found or no device token to send push notification.");
        }

        return $message;
    }
}